# SPDX-FileCopyrightText: © 2024 David Bliss
#
# SPDX-License-Identifier: GPL-3.0-or-later

version: 2
updates:
  - package-ecosystem: "cargo"
    commit-message:
      prefix: "chore(deps): "
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "chore(deps): "
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pre-commit"
    commit-message:
      prefix: "chore(deps): "
    directory: "/"
    schedule:
      interval: "daily"
