# SPDX-FileCopyrightText: © 2026 David Bliss
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: PR title conventional commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: PR title conventional commit check
        uses:  ytanikin/pr-conventional-commits@1.4.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
