# SPDX-FileCopyrightText: © 2026 David Bliss
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: PR title conventional commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: PR title conventional commit check
        uses:  ytanikin/pr-conventional-commits@639145d78959c53c43112365837e3abd21ed67c1 # 1.5.2
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
